
post http://localhost:5000/api/people/postmen
content-Type: application/json

{
    "name":"tolia"
}

###

put http://localhost:5000/api/people/2
content-Type: application/json

{
   
    "name":"simba"
}

###
delete http://localhost:5000/api/people/2
content-Type: application/json
